# Generated by Django 5.1.1 on 2024-09-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='pro.jpg', upload_to='image/'),
        ),
    ]
